@base_url = http://localhost:8000
# @base_url = https://manage-plans-server-44f92f5bfc73.herokuapp.com
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzYjRiODFhNi1mNTUyLTQ1MzYtOTQ5OC0zOTlhZTc4MzJkYjIiLCJ1c2VyRW1haWwiOiJqb2huLnNtaXRoQGV4YW1wbGUuY29tIiwiaWF0IjoxNzA5MTEzMjgxLCJleHAiOjE3MDkxMTY4ODF9.seJABwhyBm4NiO8ve56j5Tbfp70Q7e9yXCDRuSBj8RE

###
GET {{base_url}}/seed_and_sync
Content-Type: application/json

### GET /
GET {{base_url}}/

###
POST {{base_url}}/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe5@gmail.com",
  "password": "password123",
  "zipCode": "12345",
  "aboutYou": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
}


### POST /login
# Replace token variable at the top of file with token from this function  for smoother testing process below
POST {{base_url}}/login
Content-Type: application/json

{
  "email": "john.doe5@gmail.com",
  "password": "password123"
}

###
POST {{base_url}}/

### GET /plans
GET {{base_url}}/resorts


###
POST {{base_url}}/new_carpool
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzOWVjMTE4Mi00M2I1LTQ1YWUtOThlOC00OTQ2NzE2N2NjMjYiLCJ1c2VyRW1haWwiOiJqb2huLmRvZTVAZ21haWwuY29tIiwiaWF0IjoxNzQ3MDM4MzAyLCJleHAiOjE3NDcwNDE5MDJ9.aK2F396R5Bd365vY4kRsoMSBh9Wi-Ax6Uod2nmOXlDc

{
  "name": "Bluebird Powder Day Crew",
  "description": "We’re heading up early to beat the traffic and grab first tracks!",
  "meetupAddress": "123 Canyon Rd",
  "meetUpCity": "Salt Lake City",
  "meetUpState": "UT",
  "meetUpZipCode": "84121",
  "resortId": "0c35a20a-f47d-4217-953a-a056a87ab78e",
  "departureDate": "2025-01-15T06:00:00.000Z",
  "departureTime": "6:00 AM",
  "returningDate": "2025-01-15T16:00:00.000Z",
  "returningTime": "4:00 PM"
}

###
GET {{base_url}}/carpools


###
GET {{base_url}}/get_carpools_by_resort/0c35a20a-f47d-4217-953a-a056a87ab78e
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDlhN2JhNi1kYjM3LTQzZTQtYmUzZS03MzA2OTNiYmMzODgiLCJ1c2VyRW1haWwiOiJqb2huLmRvZTVAZ21haWwuY29tIiwiaWF0IjoxNzQ3MDM4MTE0LCJleHAiOjE3NDcwNDE3MTR9.XcjttId-Ge9W7J-BtRj3n3XiabOMDo9xTmuqrQBvGqc

### Get carpool conversation with messages, creator, and participants

GET {{base_url}}/get_conversation_by_carpool/01458415-bc04-4a2b-b8d1-32e33ce9aa71
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzOWVjMTE4Mi00M2I1LTQ1YWUtOThlOC00OTQ2NzE2N2NjMjYiLCJ1c2VyRW1haWwiOiJqb2huLmRvZTVAZ21haWwuY29tIiwiaWF0IjoxNzQ3MDM4NDE0LCJleHAiOjE3NDcwNDIwMTR9.Hdui8gbH2pHU85JLzmtQR01H3UD02GGcGgcGaaEdhxU

###
POST {{base_url}}/new_conversation_message
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzOWVjMTE4Mi00M2I1LTQ1YWUtOThlOC00OTQ2NzE2N2NjMjYiLCJ1c2VyRW1haWwiOiJqb2huLmRvZTVAZ21haWwuY29tIiwiaWF0IjoxNzQ3MDM4NDE0LCJleHAiOjE3NDcwNDIwMTR9.Hdui8gbH2pHU85JLzmtQR01H3UD02GGcGgcGaaEdhxU

{
  "carpoolId": "01458415-bc04-4a2b-b8d1-32e33ce9aa71",
  "messageText": "Hey everyone! Who's in for the carpool?"
}

###
POST {{base_url}}/new_conversation_message
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzOWVjMTE4Mi00M2I1LTQ1YWUtOThlOC00OTQ2NzE2N2NjMjYiLCJ1c2VyRW1haWwiOiJqb2huLmRvZTVAZ21haWwuY29tIiwiaWF0IjoxNzQ3MDM4NDE0LCJleHAiOjE3NDcwNDIwMTR9.Hdui8gbH2pHU85JLzmtQR01H3UD02GGcGgcGaaEdhxU

{
  "carpoolId": "01458415-bc04-4a2b-b8d1-32e33ce9aa71",
  "messageText": "Hoping to leave by 6:00 AM. Can take my car."
}