@base_url = http://localhost:8000
# @base_url = https://manage-plans-server-44f92f5bfc73.herokuapp.com
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzYjRiODFhNi1mNTUyLTQ1MzYtOTQ5OC0zOTlhZTc4MzJkYjIiLCJ1c2VyRW1haWwiOiJqb2huLnNtaXRoQGV4YW1wbGUuY29tIiwiaWF0IjoxNzA5MTEzMjgxLCJleHAiOjE3MDkxMTY4ODF9.seJABwhyBm4NiO8ve56j5Tbfp70Q7e9yXCDRuSBj8RE

###
GET {{base_url}}/seed_and_sync
Content-Type: application/json

### GET /
GET {{base_url}}/

###
POST {{base_url}}/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe5@gmail.com",
  "password": "password123",
  "zipCode": "12345",
  "aboutYou": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
}


### POST /login
# Replace token variable at the top of file with token from this function  for smoother testing process below
POST {{base_url}}/login
Content-Type: application/json

{
  "email": "john.doe5@gmail.com",
  "password": "password123"
}

###
POST {{base_url}}/

### GET /plans
GET {{base_url}}/resorts


###
POST {{base_url}}/new_carpool
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5Yzg0MGMyZC03N2RiLTQ0YTctODk1OS1mNmM1NGQyYjllNTAiLCJ1c2VyRW1haWwiOiJqb2huLmRvZTVAZ21haWwuY29tIiwiaWF0IjoxNzQ3MDMzNzk0LCJleHAiOjE3NDcwMzczOTR9.EYxb1b5ul-sjFZgLsGW9v1EOiLMLIBtc8xZXs_1kjdo

{
  "name": "Bluebird Powder Day Crew",
  "description": "We’re heading up early to beat the traffic and grab first tracks!",
  "meetupAddress": "123 Canyon Rd",
  "meetUpCity": "Salt Lake City",
  "meetUpState": "UT",
  "meetUpZipCode": "84121",
  "resortId": "bb4d2fef-cd71-459a-b1a2-c6b78c70797c",
  "departureDate": "2025-01-15T06:00:00.000Z",
  "departureTime": "6:00 AM",
  "returningDate": "2025-01-15T16:00:00.000Z",
  "returningTime": "4:00 PM"
}


